name: setup

description: Installs the rust toolchain.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: restore cache
      uses: actions/cache@v3
      id: toolchain-cache
      with:
        path: |
          ~/.rustup
          ~/.cargo
          target/
        key: v3::rust-toolchain::${{ runner.os }}::${{ hashFiles('**/Cargo.lock', '.github/actions/setup/action.yml') }}

    - name: install rust toolchain
      if: steps.toolchain-cache.outputs.cache-hit != 'true'
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: cargo
        target: wasm32-wasip1

    - name: install wasm-opt optimizer
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: wasm-opt

    - name: cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target wasm32-wasip1
