name: release

on:
  push:
    tags:
    - '*'

defaults:
  run:
    shell: bash

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    runs-on: ubuntu-latest
    needs: test # don't release unless tests are all passing
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup

    - name: build
      run: cargo build --release

    - name: optimize
      run: |
        if ! test -f target/wasm32-wasip1/release/datakit.wasm; then
          echo "missing output binary"
          exit 1
        fi

        wasm-opt -O4 \
          ./target/wasm32-wasip1/release/datakit.wasm \
          -o ./datakit.wasm

    - run: |
        if ! test -f ./datakit.wasm; then
          echo "missing optimized binary"
          exit 1
        fi

        readonly BODY=./body.md
        touch "$BODY"

        printf '## checksums\n\n' >> "$BODY"
        printf '```\n'            >> "$BODY"

        sha256sum \
          datakit.wasm \
          datakit.meta.json \
        >> "$BODY"

        printf '```\n'            >> "$BODY"

    - uses: ncipollo/release-action@v1
      with:
        artifacts: datakit.wasm,datakit.meta.json
        makeLatest: 'true'
        bodyFile: body.md
